// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scente.API.Data;

#nullable disable

namespace Scente.API.Migrations
{
    [DbContext(typeof(ScenteDbContext))]
    [Migration("20260508201308_AddOrderTable")]
    partial class AddOrderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Scente.API.Entity.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Scente.API.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Scente.API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("TopNotes")
                        .HasColumnType("longtext");

                    b.Property<int?>("WishlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WishlistId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseNotes = "Vetiver, Musk, Guaiac Wood, Benzoin",
                            Brand = "Orto Parisi",
                            Category = "Niche",
                            Description = "A deep, earthy fragrance with raspberry and pomegranate top notes, birch and amber in the heart, and a woody-musky base.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.45475.2x.avif",
                            MiddleNotes = "Birch, Amber, Geranium",
                            Name = "Terroni",
                            Price = 155m,
                            Status = "active",
                            Stock = 10,
                            TopNotes = "Raspberry, Pomegranate"
                        },
                        new
                        {
                            Id = 2,
                            BaseNotes = "Musk, Ambroxan, Cedar",
                            Brand = "Orto Parisi",
                            Category = "Niche",
                            Description = "An oceanic, aquatic fragrance with fresh citrus opening and a deep marine heart.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.53471.2x.avif",
                            MiddleNotes = "Seaweed, Calone, Hedione",
                            Name = "Megamare",
                            Price = 155m,
                            Status = "active",
                            Stock = 8,
                            TopNotes = "Bergamot, Lemon"
                        },
                        new
                        {
                            Id = 3,
                            BaseNotes = "Leather, Animal Notes, Incense, Labdanum, Cade oil, Patchouli, Cedar, Styrax",
                            Brand = "Orto Parisi",
                            Category = "Niche",
                            Description = "A bold leather fragrance with spicy top notes and a complex, resinous base.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.69923.2x.avif",
                            MiddleNotes = "Violet",
                            Name = "Cuoium",
                            Price = 155m,
                            Status = "active",
                            Stock = 5,
                            TopNotes = "Black Pepper, Mandarin Orange"
                        },
                        new
                        {
                            Id = 4,
                            BaseNotes = "Woody Notes, Musk",
                            Brand = "Orto Parisi",
                            Category = "Niche",
                            Description = "A fresh, green fragrance capturing the essence of nature.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.24193.2x.avif",
                            MiddleNotes = "Green Accord",
                            Name = "Viride",
                            Price = 155m,
                            Status = "active",
                            Stock = 7,
                            TopNotes = "Herbal Notes, Green Notes"
                        },
                        new
                        {
                            Id = 5,
                            BaseNotes = "Musk, Oakmoss, Ambergris, Vanille",
                            Brand = "Creed",
                            Category = "Luxury",
                            Description = "An iconic fruity-floral fragrance with pineapple and birch, perfect for the confident man.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.9828.2x.avif",
                            MiddleNotes = "Birch, Patchouli, Moroccan Jasmine, Rose",
                            Name = "Aventus",
                            Price = 235m,
                            Status = "active",
                            Stock = 15,
                            TopNotes = "Pineapple, Bergamot, Black Currant, Apple"
                        },
                        new
                        {
                            Id = 6,
                            BaseNotes = "Ambergris, Sandalwood",
                            Brand = "Creed",
                            Category = "Luxury",
                            Description = "A fresh, green fragrance inspired by the Irish countryside.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.474.2x.avif",
                            MiddleNotes = "Violet Leaf",
                            Name = "Green Irish Tweed",
                            Price = 220m,
                            Status = "active",
                            Stock = 12,
                            TopNotes = "Lemon Verbena, Iris"
                        },
                        new
                        {
                            Id = 7,
                            BaseNotes = "Musk, Petitgrain, Sandalwood, Galbanum",
                            Brand = "Creed",
                            Category = "Luxury",
                            Description = "A fresh, aquatic fragrance evoking crisp mountain air.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.472.2x.avif",
                            MiddleNotes = "Green Tea, Black Currant",
                            Name = "Silver Mountain Water",
                            Price = 220m,
                            Status = "active",
                            Stock = 9,
                            TopNotes = "Bergamot, Mandarin Orange"
                        },
                        new
                        {
                            Id = 8,
                            BaseNotes = "Sea Notes, Musk, Woody Notes",
                            Brand = "Creed",
                            Category = "Luxury",
                            Description = "A luxurious fruity-floral with sea salt and citrus notes.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.466.2x.avif",
                            MiddleNotes = "Sicilian Lemon, Bergamot, Iris, Mandarin Orange",
                            Name = "Millésime Impérial",
                            Price = 220m,
                            Status = "active",
                            Stock = 6,
                            TopNotes = "Sea Salt, Fruity Notes"
                        },
                        new
                        {
                            Id = 9,
                            BaseNotes = "Praline, Vanilla, Sandalwood",
                            Brand = "Kilian",
                            Category = "Luxury",
                            Description = "A gourmand fragrance inspired by cognac, with warm cinnamon and vanilla.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.62615.2x.avif",
                            MiddleNotes = "Cinnamon, Tonka Bean, Oak",
                            Name = "Angels' Share",
                            Price = 275m,
                            Status = "active",
                            Stock = 14,
                            TopNotes = "Cognac"
                        },
                        new
                        {
                            Id = 10,
                            BaseNotes = "Sugar, Vanilla, Caramel, Musk, Civet, Labdanum",
                            Brand = "Kilian",
                            Category = "Luxury",
                            Description = "A sweet, romantic fragrance with marshmallow and orange blossom.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.4322.2x.avif",
                            MiddleNotes = "Orange Blossom, Jasmine, Honeysuckle, Rose, Iris",
                            Name = "Love, Don't Be Shy",
                            Price = 295m,
                            Status = "active",
                            Stock = 11,
                            TopNotes = "Neroli, Bergamot, Pink Pepper, Coriander"
                        },
                        new
                        {
                            Id = 11,
                            BaseNotes = "Heliotrope, Sandalwood",
                            Brand = "Kilian",
                            Category = "Luxury",
                            Description = "A dark gourmand with rum, coffee, and chocolate notes.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.43632.2x.avif",
                            MiddleNotes = "Dark Chocolate, Coffee, Caramel, Almond",
                            Name = "Black Phantom",
                            Price = 295m,
                            Status = "active",
                            Stock = 4,
                            TopNotes = "Rum, Sugar Cane"
                        },
                        new
                        {
                            Id = 12,
                            BaseNotes = "Virginia Cedar, Musk, Amber, Vanilla",
                            Brand = "Kilian",
                            Category = "Luxury",
                            Description = "A woody-spicy fragrance with rum and dried fruits.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.4323.2x.avif",
                            MiddleNotes = "Nutmeg, Patchouli, Jasmine",
                            Name = "Straight to Heaven",
                            Price = 295m,
                            Status = "active",
                            Stock = 8,
                            TopNotes = "Dried Fruits, Rum"
                        },
                        new
                        {
                            Id = 13,
                            BaseNotes = "Ambergris, Woody Notes, Musk",
                            Brand = "Maison Francis Kurkdjian",
                            Category = "Luxury",
                            Description = "An iconic amber-woody fragrance with saffron and cedar.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.46066.2x.avif",
                            MiddleNotes = "Egyptian Jasmine, Cedar",
                            Name = "Baccarat Rouge 540 Extrait",
                            Price = 375m,
                            Status = "active",
                            Stock = 20,
                            TopNotes = "Bitter Almond, Saffron"
                        },
                        new
                        {
                            Id = 14,
                            BaseNotes = "Vanilla, Spanish Labdanum, Lavender",
                            Brand = "Maison Francis Kurkdjian",
                            Category = "Luxury",
                            Description = "A warm amber-vanilla fragrance for evening wear.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.40816.2x.avif",
                            MiddleNotes = "Tonka Bean",
                            Name = "Grand Soir",
                            Price = 205m,
                            Status = "active",
                            Stock = 13,
                            TopNotes = "Amber, Siam Benzoin"
                        },
                        new
                        {
                            Id = 15,
                            BaseNotes = "Vanilla, Agarwood (Oud), Benzoin",
                            Brand = "Maison Francis Kurkdjian",
                            Category = "Luxury",
                            Description = "A luxurious rose-oud fragrance with vanilla.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.30352.2x.avif",
                            MiddleNotes = "Bulgarian Rose, Turkish Rose",
                            Name = "Oud Satin Mood",
                            Price = 255m,
                            Status = "active",
                            Stock = 7,
                            TopNotes = "Violet"
                        },
                        new
                        {
                            Id = 16,
                            BaseNotes = "Vanilla, Amber, Musk, Woody Notes",
                            Brand = "Maison Francis Kurkdjian",
                            Category = "Luxury",
                            Description = "A spicy-vanilla fragrance with juniper berries and nutmeg.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.53401.2x.avif",
                            MiddleNotes = "Coriander",
                            Name = "Gentle Fluidity Gold",
                            Price = 205m,
                            Status = "active",
                            Stock = 9,
                            TopNotes = "Juniper Berries, Nutmeg"
                        },
                        new
                        {
                            Id = 17,
                            BaseNotes = "Vetiver, Amber, Musk, Virginia Cedar",
                            Brand = "Byredo",
                            Category = "Niche",
                            Description = "A vibrant, sunny fragrance with vetiver and African orange flower.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.6458.2x.avif",
                            MiddleNotes = "Violet, Cyclamen, Jasmine",
                            Name = "Bal d'Afrique",
                            Price = 165m,
                            Status = "active",
                            Stock = 18,
                            TopNotes = "Amalfi Lemon, Tagetes, Black Currant, Bergamot, African Orange Flower"
                        },
                        new
                        {
                            Id = 18,
                            BaseNotes = "Vanilla, Sandalwood, Amber",
                            Brand = "Byredo",
                            Category = "Niche",
                            Description = "A woody-vanilla fragrance inspired by the Romani lifestyle.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.25293.2x.avif",
                            MiddleNotes = "Pine Needles, Incense, Orris Root",
                            Name = "Gypsy Water",
                            Price = 165m,
                            Status = "active",
                            Stock = 16,
                            TopNotes = "Juniper, Lemon, Bergamot, Pepper"
                        },
                        new
                        {
                            Id = 19,
                            BaseNotes = "Ambergris, Cedar",
                            Brand = "Byredo",
                            Category = "Niche",
                            Description = "A fresh, woody fragrance inspired by the Mojave Desert.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.27040.2x.avif",
                            MiddleNotes = "Magnolia, Violet, Sandalwood",
                            Name = "Mojave Ghost",
                            Price = 165m,
                            Status = "active",
                            Stock = 14,
                            TopNotes = "Sapodilla, Ambrette (Musk Mallow)"
                        },
                        new
                        {
                            Id = 20,
                            BaseNotes = "Musk, Woody Notes, Sandalwood",
                            Brand = "Byredo",
                            Category = "Niche",
                            Description = "A clean, aldehydic floral fragrance like fresh laundry.",
                            Gender = "Women",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.6686.2x.avif",
                            MiddleNotes = "Peony, Violet, African Orange Flower",
                            Name = "Blanche",
                            Price = 165m,
                            Status = "active",
                            Stock = 11,
                            TopNotes = "Aldehydes, Rose, Pink Pepper"
                        },
                        new
                        {
                            Id = 21,
                            BaseNotes = "Leather, Agarwood (Oud), Patchouli, Sandalwood",
                            Brand = "Amouage",
                            Category = "Luxury",
                            Description = "A bold, smoky fragrance with oregano and leather.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.15294.2x.avif",
                            MiddleNotes = "Incense, Amber, Labdanum, Opoponax",
                            Name = "Interlude Man",
                            Price = 395m,
                            Status = "active",
                            Stock = 5,
                            TopNotes = "Oregano, Pepper, Bergamot"
                        },
                        new
                        {
                            Id = 22,
                            BaseNotes = "Sandalwood, Vetiver, Cedar, Patchouli",
                            Brand = "Amouage",
                            Category = "Luxury",
                            Description = "A sophisticated floral-woody fragrance.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.920.2x.avif",
                            MiddleNotes = "Jasmine, Neroli, Orris Root, Ylang-Ylang",
                            Name = "Reflection Man",
                            Price = 395m,
                            Status = "active",
                            Stock = 6,
                            TopNotes = "Rosemary, Pink Pepper, Petitgrain"
                        },
                        new
                        {
                            Id = 23,
                            BaseNotes = "Myrrh, Agarwood (Oud), Opoponax, Patchouli, Ambergris, Cedar, Musk",
                            Brand = "Amouage",
                            Category = "Luxury",
                            Description = "A complex, fruity-woody fragrance with blackberry and myrrh.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.2366.2x.avif",
                            MiddleNotes = "Honey, Guaiac Wood, Cinnamon, Bay Leaf, Clove, Rose, Orchid",
                            Name = "Jubilation XXV",
                            Price = 395m,
                            Status = "active",
                            Stock = 4,
                            TopNotes = "Blackberry, Olibanum, Orange, Coriander, Labdanum, Tarragon"
                        },
                        new
                        {
                            Id = 24,
                            BaseNotes = "Agarwood (Oud), Incense, Patchouli, Guaiac Wood, Orris Root, Sandalwood, Amber, Vanilla, Musk",
                            Brand = "Amouage",
                            Category = "Luxury",
                            Description = "A spicy-woody fragrance with rose and oud.",
                            Gender = "Women",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.6538.2x.avif",
                            MiddleNotes = "Rose, Geranium, Jasmine, Tea",
                            Name = "Epic Woman",
                            Price = 395m,
                            Status = "active",
                            Stock = 8,
                            TopNotes = "Caraway, Pink Pepper, Cinnamon"
                        },
                        new
                        {
                            Id = 25,
                            BaseNotes = "Ambergris, Benzoin, Musk",
                            Brand = "Zoologist",
                            Category = "Niche",
                            Description = "An oceanic-amber fragrance with ink and ambergris.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.56294.2x.avif",
                            MiddleNotes = "Sea Salt, Ink, Opoponax",
                            Name = "Squid",
                            Price = 200m,
                            Status = "active",
                            Stock = 7,
                            TopNotes = "Incense, Pink Pepper, Salicylate"
                        },
                        new
                        {
                            Id = 26,
                            BaseNotes = "Cade Oil, Leather, Resins, Civet, Amber, Cedar, Frankincense, Patchouli, Sandalwood, Vanilla",
                            Brand = "Zoologist",
                            Category = "Niche",
                            Description = "A fiery, metallic fragrance with smoke and leather.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.51353.2x.avif",
                            MiddleNotes = "Champaca, Geranium, Jasmine, Osmanthus, Rose, Ylang-Ylang",
                            Name = "T-Rex",
                            Price = 240m,
                            Status = "active",
                            Stock = 3,
                            TopNotes = "Bay Leaf, Black Pepper, Bergamot, Pine, Neroli, Nutmeg"
                        },
                        new
                        {
                            Id = 27,
                            BaseNotes = "Benzoin, Labdanum, Musks, Sandalwood, Vanilla",
                            Brand = "Zoologist",
                            Category = "Niche",
                            Description = "A sweet, honey-forward fragrance with royal jelly.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.58140.2x.avif",
                            MiddleNotes = "Broom, Heliotrope, Mimosa, Orange Blossom",
                            Name = "Bee",
                            Price = 240m,
                            Status = "active",
                            Stock = 6,
                            TopNotes = "Orange, Ginger Syrup, Royal Jelly Accord"
                        },
                        new
                        {
                            Id = 28,
                            BaseNotes = "Ambergris, Benzoin, Cypriol Oil, Guaiac Wood, Honey, Musk, Patchouli, Resins, Smoke",
                            Brand = "Zoologist",
                            Category = "Niche",
                            Description = "A dark, powdery fragrance with smoke and honey.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.49270.2x.avif",
                            MiddleNotes = "Heliotrope, Iris, Jasmine, Mimosa, Rose",
                            Name = "Moth",
                            Price = 200m,
                            Status = "active",
                            Stock = 5,
                            TopNotes = "Black Pepper, Clove, Cumin, Lemon, Nutmeg, Saffron"
                        },
                        new
                        {
                            Id = 29,
                            BaseNotes = "Patchouli, Musk",
                            Brand = "Initio",
                            Category = "Niche",
                            Description = "A powerful oud-saffron fragrance with nutmeg and lavender.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.53641.2x.avif",
                            MiddleNotes = "Agarwood (Oud)",
                            Name = "Oud for Greatness",
                            Price = 250m,
                            Status = "active",
                            Stock = 12,
                            TopNotes = "Saffron, Nutmeg, Lavender"
                        },
                        new
                        {
                            Id = 30,
                            BaseNotes = "Cinnamon",
                            Brand = "Initio",
                            Category = "Niche",
                            Description = "A boozy, tobacco-vanilla fragrance with cinnamon.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.42260.2x.avif",
                            MiddleNotes = "Tobacco",
                            Name = "Side Effect",
                            Price = 220m,
                            Status = "active",
                            Stock = 10,
                            TopNotes = "Rum, Vanilla"
                        },
                        new
                        {
                            Id = 31,
                            BaseNotes = "Black Currant, Sandalwood, Pink Musk",
                            Brand = "Initio",
                            Category = "Niche",
                            Description = "A clean, white musk fragrance with citrus and magnolia.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.66097.2x.avif",
                            MiddleNotes = "Mandarin Orange, Magnolia",
                            Name = "Musk Therapy",
                            Price = 230m,
                            Status = "active",
                            Stock = 9,
                            TopNotes = "White Musk, Bergamot"
                        },
                        new
                        {
                            Id = 32,
                            BaseNotes = "Sandalwood, Musk, Guaiac Wood",
                            Brand = "Initio",
                            Category = "Niche",
                            Description = "A fresh, lavender-based fragrance with vetiver and sandalwood.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.50351.2x.avif",
                            MiddleNotes = "Vetiver, Patchouli, Cedar",
                            Name = "Rehab",
                            Price = 290m,
                            Status = "active",
                            Stock = 8,
                            TopNotes = "Lavender, Bergamot"
                        },
                        new
                        {
                            Id = 33,
                            BaseNotes = "Agarwood (Oud), Cedar, Leather, Sandalwood, Amber, Musk, Tonka Bean, Vanilla",
                            Brand = "Penhaligon's",
                            Category = "Luxury",
                            Description = "A dark, spicy-woody fragrance with rose and oud.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.31396.2x.avif",
                            MiddleNotes = "Bulgarian Rose, Nutmeg, Jasmine",
                            Name = "Halfeti",
                            Price = 245m,
                            Status = "active",
                            Stock = 11,
                            TopNotes = "Cypress Leaf, Saffron, Cardamom, Artemisia, Bergamot, Grapefruit"
                        },
                        new
                        {
                            Id = 34,
                            BaseNotes = "Amber, Tonka Bean",
                            Brand = "Penhaligon's",
                            Category = "Luxury",
                            Description = "A sophisticated brandy-amber fragrance with shaving soap notes.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.40716.2x.avif",
                            MiddleNotes = "Woodsy Notes, Shaving Soap",
                            Name = "The Tragedy of Lord George",
                            Price = 275m,
                            Status = "active",
                            Stock = 6,
                            TopNotes = "Brandy"
                        },
                        new
                        {
                            Id = 35,
                            BaseNotes = "Sandalwood, Leather, Myrrh, Musk, Vetiver, Cardamom, Pepper, Olibanum",
                            Brand = "Penhaligon's",
                            Category = "Luxury",
                            Description = "A lavender-coffee fragrance with leather and sandalwood.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.5674.2x.avif",
                            MiddleNotes = "Coffee, Geranium",
                            Name = "Endymion",
                            Price = 160m,
                            Status = "active",
                            Stock = 13,
                            TopNotes = "Lavender, Bergamot, Sage, Mandarin Orange"
                        },
                        new
                        {
                            Id = 36,
                            BaseNotes = "Incense, Tonka Bean",
                            Brand = "Penhaligon's",
                            Category = "Luxury",
                            Description = "A vanilla-incense fragrance with grapefruit and ambrette.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.71646.2x.avif",
                            MiddleNotes = "Ambrette (Musk Mallow), Clary Sage",
                            Name = "The World According To Arthur",
                            Price = 275m,
                            Status = "active",
                            Stock = 5,
                            TopNotes = "Vanilla, Grapefruit"
                        },
                        new
                        {
                            Id = 37,
                            BaseNotes = "Vanilla, Cardamom, Sandalwood, Pepper, Patchouli, Guaiac Wood",
                            Brand = "Parfums de Marly",
                            Category = "Luxury",
                            Description = "A fresh, apple-lavender fragrance with vanilla and cardamom.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.39314.2x.avif",
                            MiddleNotes = "Geranium, Violet, Jasmine",
                            Name = "Layton",
                            Price = 225m,
                            Status = "active",
                            Stock = 18,
                            TopNotes = "Apple, Lavender, Bergamot, Mandarin Orange"
                        },
                        new
                        {
                            Id = 38,
                            BaseNotes = "Agarwood (Oud), Cedar",
                            Brand = "Parfums de Marly",
                            Category = "Luxury",
                            Description = "An oud-praline fragrance with clary sage and lavender.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.70776.2x.avif",
                            MiddleNotes = "Saffron, Praline",
                            Name = "Haltane",
                            Price = 275m,
                            Status = "active",
                            Stock = 7,
                            TopNotes = "Clary Sage, Lavender, Bergamot"
                        },
                        new
                        {
                            Id = 39,
                            BaseNotes = "Vanilla, Iso E Super, Musk, Cedar, Cypriol Oil, Vetiver",
                            Brand = "Parfums de Marly",
                            Category = "Luxury",
                            Description = "A warm, spicy-vanilla fragrance with cinnamon and tobacco.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.16939.2x.avif",
                            MiddleNotes = "Tobacco Leaf, Incense, Osmanthus, Labdanum",
                            Name = "Herod",
                            Price = 225m,
                            Status = "active",
                            Stock = 14,
                            TopNotes = "Cinnamon, Pepper"
                        },
                        new
                        {
                            Id = 40,
                            BaseNotes = "Cashmeran, Haitian Vetiver, Cedar, Incense",
                            Brand = "Parfums de Marly",
                            Category = "Luxury",
                            Description = "A vibrant floral-fruity fragrance with rose and lychee.",
                            Gender = "Women",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.43871.2x.avif",
                            MiddleNotes = "Turkish Rose, Peony, Petalia, Vanilla, Musk",
                            Name = "Delina",
                            Price = 285m,
                            Status = "active",
                            Stock = 16,
                            TopNotes = "Rhubarb, Litchi, Bergamot, Nutmeg"
                        },
                        new
                        {
                            Id = 41,
                            BaseNotes = "Oakmoss, Woody Notes",
                            Brand = "Nishane",
                            Category = "Niche",
                            Description = "A fresh pineapple and cedar fragrance with oakmoss depth.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.44174.2x.avif",
                            MiddleNotes = "Cedar, Patchouli, Jasmine",
                            Name = "Hacivat",
                            Price = 280m,
                            Status = "active",
                            Stock = 11,
                            TopNotes = "Pineapple, Grapefruit, Bergamot"
                        },
                        new
                        {
                            Id = 42,
                            BaseNotes = "Vanilla, Benzoin, Sandalwood, Musk, Patchouli, Cedar, Ambergris",
                            Brand = "Nishane",
                            Category = "Niche",
                            Description = "A complex spicy-floral fragrance with rose and vanilla.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.54785.2x.avif",
                            MiddleNotes = "Cardamom, Black Currant, Turkish Rose",
                            Name = "Ani",
                            Price = 260m,
                            Status = "active",
                            Stock = 9,
                            TopNotes = "Ginger, Bergamot, Pink Pepper, Green Notes"
                        },
                        new
                        {
                            Id = 43,
                            BaseNotes = "Fig, Musk",
                            Brand = "Nishane",
                            Category = "Niche",
                            Description = "A delicate tea fragrance with citrus and fig.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.30567.2x.avif",
                            MiddleNotes = "Tea, Nutmeg",
                            Name = "Wulong Cha",
                            Price = 260m,
                            Status = "active",
                            Stock = 8,
                            TopNotes = "Bergamot, Orange, Mandarin Orange, Litchi"
                        },
                        new
                        {
                            Id = 44,
                            BaseNotes = "Chinese Cedar, Oakmoss",
                            Brand = "Nishane",
                            Category = "Niche",
                            Description = "A warm, tropical fragrance with coconut and tobacco.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.37603.2x.avif",
                            MiddleNotes = "Tobacco, Tonka Bean",
                            Name = "Fan Your Flames",
                            Price = 260m,
                            Status = "active",
                            Stock = 7,
                            TopNotes = "Coconut, Rum"
                        },
                        new
                        {
                            Id = 45,
                            BaseNotes = "Agarwood (Oud), Incense",
                            Brand = "Nasomatto",
                            Category = "Niche",
                            Description = "A dark, resinous fragrance with oud and incense.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.6472.2x.avif",
                            MiddleNotes = "Resins, Woodsy Notes, Tobacco, Coffee",
                            Name = "Black Afgano",
                            Price = 130m,
                            Status = "active",
                            Stock = 9,
                            TopNotes = "Cannabis, Green Notes"
                        },
                        new
                        {
                            Id = 46,
                            BaseNotes = "Woody Notes, Musk, Ambrette (Musk Mallow), Ambroxan",
                            Brand = "Nasomatto",
                            Category = "Niche",
                            Description = "A boozy, rose-tinged fragrance with woody musk.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.40200.2x.avif",
                            MiddleNotes = "Rose",
                            Name = "Baraonda",
                            Price = 130m,
                            Status = "active",
                            Stock = 7,
                            TopNotes = "Whiskey"
                        },
                        new
                        {
                            Id = 47,
                            BaseNotes = "Agarwood (Oud), Sandalwood",
                            Brand = "Nasomatto",
                            Category = "Niche",
                            Description = "A floral-chocolate fragrance with oud warmth.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.12130.2x.avif",
                            MiddleNotes = "Dark Chocolate, Tonka Bean, Cinnamon",
                            Name = "Pardon",
                            Price = 130m,
                            Status = "active",
                            Stock = 6,
                            TopNotes = "Magnolia, Flowers"
                        },
                        new
                        {
                            Id = 48,
                            BaseNotes = "Woody Notes",
                            Brand = "Nasomatto",
                            Category = "Niche",
                            Description = "A bold leather and woody spice fragrance.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.4291.2x.avif",
                            MiddleNotes = "Spices",
                            Name = "Duro",
                            Price = 130m,
                            Status = "active",
                            Stock = 5,
                            TopNotes = "Leather"
                        },
                        new
                        {
                            Id = 49,
                            BaseNotes = "White Musk",
                            Brand = "Etat Libre d'Orange",
                            Category = "Niche",
                            Description = "A fresh, green-aquatic fragrance with mint and white musk.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.43531.2x.avif",
                            MiddleNotes = "Green Notes, Cassis, Rose, Hedione",
                            Name = "You Or Someone Like You",
                            Price = 105m,
                            Status = "active",
                            Stock = 12,
                            TopNotes = "Mint, Grapefruit, Bergamot, Anise"
                        },
                        new
                        {
                            Id = 50,
                            BaseNotes = "Vanilla, Opoponax, Chestnut",
                            Brand = "Etat Libre d'Orange",
                            Category = "Niche",
                            Description = "A creamy vetiver fragrance with myrrh and vanilla.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.7139.2x.avif",
                            MiddleNotes = "Myrrh, Olive Leaf",
                            Name = "Fat Electrician",
                            Price = 105m,
                            Status = "active",
                            Stock = 10,
                            TopNotes = "Vetiver, Whipped Cream"
                        },
                        new
                        {
                            Id = 51,
                            BaseNotes = "Iris, Coconut, Opoponax",
                            Brand = "Etat Libre d'Orange",
                            Category = "Niche",
                            Description = "A radically avant-garde fragrance — not for the faint-hearted.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.4523.2x.avif",
                            MiddleNotes = "Milk, Adrenaline, Blood",
                            Name = "Secretions Magnifiques",
                            Price = 105m,
                            Status = "active",
                            Stock = 8,
                            TopNotes = "Seaweed, Iodine"
                        },
                        new
                        {
                            Id = 52,
                            BaseNotes = "Sandalwood, Lorenox, Labdanum",
                            Brand = "Etat Libre d'Orange",
                            Category = "Niche",
                            Description = "A spicy, effervescent fragrance with cardamom and jasmine.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.30504.2x.avif",
                            MiddleNotes = "Curry Tree, Black Pepper, Jasmine",
                            Name = "Remarkable People",
                            Price = 105m,
                            Status = "active",
                            Stock = 14,
                            TopNotes = "Champagne, Grapefruit, Cardamom"
                        },
                        new
                        {
                            Id = 53,
                            BaseNotes = "Tobacco Leaf, Vanilla, Tonka Bean",
                            Brand = "Xerjoff",
                            Category = "Luxury",
                            Description = "A honeyed lavender fragrance with tobacco and vanilla.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.30529.2x.avif",
                            MiddleNotes = "Honey, Cinnamon, Cashmeran, Jasmine Sambac",
                            Name = "Naxos",
                            Price = 200m,
                            Status = "active",
                            Stock = 9,
                            TopNotes = "Lavender, Bergamot, Lemon"
                        },
                        new
                        {
                            Id = 54,
                            BaseNotes = "Agarwood (Oud), Sandalwood, Vanilla, Amber, Musk",
                            Brand = "Xerjoff",
                            Category = "Luxury",
                            Description = "A rich, oriental fragrance with oud, rose, and cedar.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.17786.2x.avif",
                            MiddleNotes = "Rose, Cedar, Lily-of-the-Valley",
                            Name = "Alexandria II",
                            Price = 266m,
                            Status = "active",
                            Stock = 7,
                            TopNotes = "Palisander Rosewood, Lavender, Cinnamon, Apple"
                        },
                        new
                        {
                            Id = 55,
                            BaseNotes = "White Musk, Madagascar Vanilla, Amber",
                            Brand = "Xerjoff",
                            Category = "Luxury",
                            Description = "A sunny, citrus-vanilla fragrance bursting with Mediterranean warmth.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.55157.2x.avif",
                            MiddleNotes = "Fruits",
                            Name = "Erba Pura",
                            Price = 135m,
                            Status = "active",
                            Stock = 15,
                            TopNotes = "Sicilian Orange, Calabrian Bergamot, Sicilian Lemon"
                        },
                        new
                        {
                            Id = 56,
                            BaseNotes = "Musk, Amber, Virginia Cedar, Patchouli",
                            Brand = "Xerjoff",
                            Category = "Luxury",
                            Description = "A fresh citrus fragrance with floral heart and woody base.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.12126.2x.avif",
                            MiddleNotes = "Mint, Lily-of-the-Valley, Rose",
                            Name = "Renaissance",
                            Price = 200m,
                            Status = "active",
                            Stock = 8,
                            TopNotes = "Amalfi Lemon, Tangerine, Bergamot, Petitgrain"
                        },
                        new
                        {
                            Id = 57,
                            BaseNotes = "Ambrofix",
                            Brand = "Tom Ford",
                            Category = "Luxury",
                            Description = "A sleek, modern leather fragrance with spiced warmth.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.95389.2x.avif",
                            MiddleNotes = "Vanilla, Leather",
                            Name = "Eau d'Ombré Leather",
                            Price = 140m,
                            Status = "active",
                            Stock = 12,
                            TopNotes = "Cardamom, Ginger, Coriander"
                        },
                        new
                        {
                            Id = 58,
                            BaseNotes = "Vetiver, Oakmoss, Amber",
                            Brand = "Tom Ford",
                            Category = "Luxury",
                            Description = "A sophisticated vetiver fragrance with citrus and oakmoss.",
                            Gender = "Men",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.6697.2x.avif",
                            MiddleNotes = "Nutmeg, Orris Root, Pimento",
                            Name = "Grey Vetiver",
                            Price = 165m,
                            Status = "active",
                            Stock = 10,
                            TopNotes = "Grapefruit, Orange Blossom, Sage"
                        },
                        new
                        {
                            Id = 59,
                            BaseNotes = "Incense, Vetiver, Oak",
                            Brand = "Tom Ford",
                            Category = "Luxury",
                            Description = "A coastal, woody fragrance inspired by the Italian Riviera.",
                            Gender = "Unisex",
                            Image = "https://fimgs.net/mdimg/perfume-thumbs/dark-375x500.64617.2x.avif",
                            MiddleNotes = "Cypress, Lemon, Yellow Mandarin, Lavender",
                            Name = "Costa Azzurra",
                            Price = 165m,
                            Status = "active",
                            Stock = 9,
                            TopNotes = "Driftwood, Seaweed, Agarwood"
                        });
                });

            modelBuilder.Entity("Scente.API.Entity.ProductVolume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVolumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 155m,
                            ProductId = 1,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 2,
                            Price = 155m,
                            ProductId = 2,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 3,
                            Price = 155m,
                            ProductId = 3,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 4,
                            Price = 155m,
                            ProductId = 4,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 5,
                            Price = 170m,
                            ProductId = 5,
                            Size = "30ml"
                        },
                        new
                        {
                            Id = 6,
                            Price = 235m,
                            ProductId = 5,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 7,
                            Price = 330m,
                            ProductId = 5,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 8,
                            Price = 220m,
                            ProductId = 6,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 9,
                            Price = 320m,
                            ProductId = 6,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 10,
                            Price = 165m,
                            ProductId = 7,
                            Size = "30ml"
                        },
                        new
                        {
                            Id = 11,
                            Price = 220m,
                            ProductId = 7,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 12,
                            Price = 320m,
                            ProductId = 7,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 13,
                            Price = 220m,
                            ProductId = 8,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 14,
                            Price = 320m,
                            ProductId = 8,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 15,
                            Price = 275m,
                            ProductId = 9,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 16,
                            Price = 415m,
                            ProductId = 9,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 17,
                            Price = 295m,
                            ProductId = 10,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 18,
                            Price = 450m,
                            ProductId = 10,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 19,
                            Price = 295m,
                            ProductId = 11,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 20,
                            Price = 450m,
                            ProductId = 11,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 21,
                            Price = 295m,
                            ProductId = 12,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 22,
                            Price = 450m,
                            ProductId = 12,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 23,
                            Price = 245m,
                            ProductId = 13,
                            Size = "35ml"
                        },
                        new
                        {
                            Id = 24,
                            Price = 375m,
                            ProductId = 13,
                            Size = "70ml"
                        },
                        new
                        {
                            Id = 25,
                            Price = 135m,
                            ProductId = 14,
                            Size = "35ml"
                        },
                        new
                        {
                            Id = 26,
                            Price = 205m,
                            ProductId = 14,
                            Size = "70ml"
                        },
                        new
                        {
                            Id = 27,
                            Price = 165m,
                            ProductId = 15,
                            Size = "35ml"
                        },
                        new
                        {
                            Id = 28,
                            Price = 255m,
                            ProductId = 15,
                            Size = "70ml"
                        },
                        new
                        {
                            Id = 29,
                            Price = 135m,
                            ProductId = 16,
                            Size = "35ml"
                        },
                        new
                        {
                            Id = 30,
                            Price = 205m,
                            ProductId = 16,
                            Size = "70ml"
                        },
                        new
                        {
                            Id = 31,
                            Price = 165m,
                            ProductId = 17,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 32,
                            Price = 240m,
                            ProductId = 17,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 33,
                            Price = 165m,
                            ProductId = 18,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 34,
                            Price = 240m,
                            ProductId = 18,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 35,
                            Price = 165m,
                            ProductId = 19,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 36,
                            Price = 240m,
                            ProductId = 19,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 37,
                            Price = 165m,
                            ProductId = 20,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 38,
                            Price = 240m,
                            ProductId = 20,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 39,
                            Price = 395m,
                            ProductId = 21,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 40,
                            Price = 395m,
                            ProductId = 22,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 41,
                            Price = 395m,
                            ProductId = 23,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 42,
                            Price = 395m,
                            ProductId = 24,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 43,
                            Price = 200m,
                            ProductId = 25,
                            Size = "60ml"
                        },
                        new
                        {
                            Id = 44,
                            Price = 240m,
                            ProductId = 26,
                            Size = "60ml"
                        },
                        new
                        {
                            Id = 45,
                            Price = 240m,
                            ProductId = 27,
                            Size = "60ml"
                        },
                        new
                        {
                            Id = 46,
                            Price = 200m,
                            ProductId = 28,
                            Size = "60ml"
                        },
                        new
                        {
                            Id = 47,
                            Price = 250m,
                            ProductId = 29,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 48,
                            Price = 320m,
                            ProductId = 29,
                            Size = "90ml"
                        },
                        new
                        {
                            Id = 49,
                            Price = 220m,
                            ProductId = 30,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 50,
                            Price = 280m,
                            ProductId = 30,
                            Size = "90ml"
                        },
                        new
                        {
                            Id = 51,
                            Price = 230m,
                            ProductId = 31,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 52,
                            Price = 290m,
                            ProductId = 31,
                            Size = "90ml"
                        },
                        new
                        {
                            Id = 53,
                            Price = 290m,
                            ProductId = 32,
                            Size = "90ml"
                        },
                        new
                        {
                            Id = 54,
                            Price = 245m,
                            ProductId = 33,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 55,
                            Price = 275m,
                            ProductId = 34,
                            Size = "75ml"
                        },
                        new
                        {
                            Id = 56,
                            Price = 83m,
                            ProductId = 35,
                            Size = "30ml"
                        },
                        new
                        {
                            Id = 57,
                            Price = 160m,
                            ProductId = 35,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 58,
                            Price = 275m,
                            ProductId = 36,
                            Size = "75ml"
                        },
                        new
                        {
                            Id = 59,
                            Price = 225m,
                            ProductId = 37,
                            Size = "75ml"
                        },
                        new
                        {
                            Id = 60,
                            Price = 290m,
                            ProductId = 37,
                            Size = "125ml"
                        },
                        new
                        {
                            Id = 61,
                            Price = 275m,
                            ProductId = 38,
                            Size = "75ml"
                        },
                        new
                        {
                            Id = 62,
                            Price = 325m,
                            ProductId = 38,
                            Size = "125ml"
                        },
                        new
                        {
                            Id = 63,
                            Price = 225m,
                            ProductId = 39,
                            Size = "75ml"
                        },
                        new
                        {
                            Id = 64,
                            Price = 290m,
                            ProductId = 39,
                            Size = "125ml"
                        },
                        new
                        {
                            Id = 65,
                            Price = 180m,
                            ProductId = 40,
                            Size = "30ml"
                        },
                        new
                        {
                            Id = 66,
                            Price = 285m,
                            ProductId = 40,
                            Size = "75ml"
                        },
                        new
                        {
                            Id = 67,
                            Price = 280m,
                            ProductId = 41,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 68,
                            Price = 395m,
                            ProductId = 41,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 69,
                            Price = 260m,
                            ProductId = 42,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 70,
                            Price = 375m,
                            ProductId = 42,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 71,
                            Price = 260m,
                            ProductId = 43,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 72,
                            Price = 375m,
                            ProductId = 43,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 73,
                            Price = 260m,
                            ProductId = 44,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 74,
                            Price = 375m,
                            ProductId = 44,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 75,
                            Price = 130m,
                            ProductId = 45,
                            Size = "30ml"
                        },
                        new
                        {
                            Id = 76,
                            Price = 130m,
                            ProductId = 46,
                            Size = "30ml"
                        },
                        new
                        {
                            Id = 77,
                            Price = 130m,
                            ProductId = 47,
                            Size = "30ml"
                        },
                        new
                        {
                            Id = 78,
                            Price = 130m,
                            ProductId = 48,
                            Size = "30ml"
                        },
                        new
                        {
                            Id = 79,
                            Price = 105m,
                            ProductId = 49,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 80,
                            Price = 160m,
                            ProductId = 49,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 81,
                            Price = 105m,
                            ProductId = 50,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 82,
                            Price = 160m,
                            ProductId = 50,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 83,
                            Price = 105m,
                            ProductId = 51,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 84,
                            Price = 105m,
                            ProductId = 52,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 85,
                            Price = 160m,
                            ProductId = 52,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 86,
                            Price = 200m,
                            ProductId = 53,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 87,
                            Price = 266m,
                            ProductId = 54,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 88,
                            Price = 446m,
                            ProductId = 54,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 89,
                            Price = 135m,
                            ProductId = 55,
                            Size = "50ml"
                        },
                        new
                        {
                            Id = 90,
                            Price = 200m,
                            ProductId = 55,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 91,
                            Price = 200m,
                            ProductId = 56,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 92,
                            Price = 140m,
                            ProductId = 57,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 93,
                            Price = 165m,
                            ProductId = 58,
                            Size = "100ml"
                        },
                        new
                        {
                            Id = 94,
                            Price = 165m,
                            ProductId = 59,
                            Size = "100ml"
                        });
                });

            modelBuilder.Entity("Scente.API.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Scente.API.Entity.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Scente.API.Entity.Cart", b =>
                {
                    b.HasOne("Scente.API.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scente.API.Entity.Order", b =>
                {
                    b.HasOne("Scente.API.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scente.API.Entity.Product", b =>
                {
                    b.HasOne("Scente.API.Entity.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("Scente.API.Entity.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("Scente.API.Entity.Wishlist", null)
                        .WithMany("Items")
                        .HasForeignKey("WishlistId");
                });

            modelBuilder.Entity("Scente.API.Entity.ProductVolume", b =>
                {
                    b.HasOne("Scente.API.Entity.Product", "Product")
                        .WithMany("Volumes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Scente.API.Entity.Wishlist", b =>
                {
                    b.HasOne("Scente.API.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scente.API.Entity.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Scente.API.Entity.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Scente.API.Entity.Product", b =>
                {
                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Scente.API.Entity.Wishlist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
